### ISSUE TITLE
cockroachdb 1.0 is out, cut a new release

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry-community/cockroachdb-release#1]
Hello
version 1.0 of cockroach is out
https://www.cockroachlabs.com/blog/cockroachdb-1-0-release/
Interested in common work to cut an updated bosh release ?

**Comment by robdimsdale** [comment]
@poblin-orange I wonder if @cppforlife has thoughts on deprecating this in favor of: https://github.com/cppforlife/cockroachdb-release - that seems more maintained than this.

**Comment by poblin-orange** [comment]
@cppforlife your release takes benefits of most bosh2 features. Would you agree for a merge and publish to cloudfoundry-community ?

**Comment by shinji62** [comment]
@poblin-orange  @robdimsdale  @cppforlife Agree, even I would prefer to entirely deprecate this one instead of merging it.

**Comment by cppforlife** [comment]
i would prefer keeping it not merged but deprecating this repo. i m definitely happy to take prs.

**Comment by cunnie** [comment]
I'm closing this issue; we've put a deprecation notice on the README pointing to Dmitriy's release.
